app_images:
- appImageId: 45f71d0ea7974963ab5c6da617e4930f
  flavourName: vanilla
  image:
    buildAt: '2026-04-14T20:28:05.100596'
    imageString: jhnnsrs/starmist:0.0.6-vanilla
  inspection:
    implementations:
    - definition:
        args:
        - description: The Input Image (needs to have at least 3 channels).
          effects: []
          identifier: '@mikro/image'
          key: image
          kind: STRUCTURE
          label: image
          nullable: false
          validators: []
          widget:
            kind: SEARCH
            query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
              \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
              \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
              \    __typename\n  }\n}"
            ward: mikro
        collections:
        - segmentation
        - prediction
        - nuclei
        description: Segments Cells using the stardist he pretrained model
        interfaces: []
        isDev: false
        isTestFor: []
        key: predict_stardist_he
        kind: FUNCTION
        name: Segment HE
        portGroups: []
        returns:
        - description: An Image with the Segmented Cells.
          effects: []
          identifier: '@mikro/image'
          key: return0
          kind: STRUCTURE
          label: return0
          nullable: false
          validators: []
        stateful: true
        version: '1'
      dependencies: []
      dynamic: false
      interface: predict_stardist_he
      locks: []
      optimistics: []
    - definition:
        args:
        - description: The Input Image.
          effects: []
          identifier: '@mikro/image'
          key: image
          kind: STRUCTURE
          label: image
          nullable: false
          validators: []
          widget:
            kind: SEARCH
            query: "query SearchImages($search: String, $values: [ID!]) {\n  options:\
              \ images(\n    filters: {name: {contains: $search}, ids: $values}\n\
              \    pagination: {limit: 10}\n  ) {\n    value: id\n    label: name\n\
              \    __typename\n  }\n}"
            ward: mikro
        collections:
        - segmentation
        - prediction
        - nuclei
        description: Segments Cells using the stardist flou2 pretrained model
        interfaces: []
        isDev: false
        isTestFor: []
        key: predict_flou2
        kind: FUNCTION
        name: Segment Flou2
        portGroups: []
        returns:
        - description: An Image with the Segmented Cells.
          effects: []
          identifier: '@mikro/image'
          key: return0
          kind: STRUCTURE
          label: return0
          nullable: false
          validators: []
        stateful: true
        version: '1'
      dependencies: []
      dynamic: false
      interface: predict_flou2
      locks: []
      optimistics: []
    locks: []
    requirements:
    - description: An instance of ArkitektNext Mikro to make requests to the user's
        data
      key: mikro
      optional: false
      service: live.arkitekt.mikro
    - description: An instance of ArkitektNext Rekuest to assign to actions
      key: rekuest
      optional: false
      service: live.arkitekt.rekuest
    - description: An instance of ArkitektNext Rekuest to assign to actions
      key: s3
      optional: false
      service: live.arkitekt.s3
    size: 16222418752
    states: []
  manifest:
    author: jhnnsrs
    identifier: starmist
    scopes:
    - read
    version: 0.0.6
  selectors:
  - kind: cuda
latest_app_image: 45f71d0ea7974963ab5c6da617e4930f
